#!/bin/bash

REPOSITORY_ID=itm-maven-repository-releases
REPOSITORY_URL=scp://itm01.itm.uni-luebeck.de/www/itm/projects/maven/releases

mvn deploy:deploy-file \
 -DgroupId=org.eclipse \
 -DartifactId=org.eclipse.ui.workbench \
 -Dversion=3.4.0 \
 -Dpackaging=jar \
 -Dfile=lib/org.eclipse.ui.workbench_3.4.0.I20080606-1300.jar \
 -DrepositoryId=$REPOSITORY_ID \
 -Durl=$REPOSITORY_URL
 
 mvn deploy:deploy-file \
 -DgroupId=org.eclipse \
 -DartifactId=org.eclipse.ui.forms \
 -Dversion=3.3.100 \
 -Dpackaging=jar \
 -Dfile=lib/org.eclipse.ui.forms_3.3.100.v20080611.jar \
 -DrepositoryId=$REPOSITORY_ID \
 -Durl=$REPOSITORY_URL
 
 mvn deploy:deploy-file \
 -DgroupId=org.eclipse \
 -DartifactId=org.eclipse.osgi \
 -Dversion=3.4.0 \
 -Dpackaging=jar \
 -Dfile=lib/org.eclipse.osgi_3.4.0.v20080605-1900.jar \
 -DrepositoryId=$REPOSITORY_ID \
 -Durl=$REPOSITORY_URL
 
mvn deploy:deploy-file \
 -DgroupId=org.eclipse \
 -DartifactId=org.eclipse.jface \
 -Dversion=3.4.0 \
 -Dpackaging=jar \
 -Dfile=lib/org.eclipse.jface_3.4.0.I20080606-1300.jar \
 -DrepositoryId=$REPOSITORY_ID \
 -Durl=$REPOSITORY_URL
 
 mvn deploy:deploy-file \
 -DgroupId=org.eclipse \
 -DartifactId=org.eclipse.equinox.common \
 -Dversion=3.3.0 \
 -Dpackaging=jar \
 -Dfile=lib/org.eclipse.equinox.common_3.3.0.v20070426.jar \
 -DrepositoryId=$REPOSITORY_ID \
 -Durl=$REPOSITORY_URL
 
mvn deploy:deploy-file \
 -DgroupId=org.eclipse \
 -DartifactId=org.eclipse.core.runtime \
 -Dversion=3.4.0 \
 -Dpackaging=jar \
 -Dfile=lib/org.eclipse.core.runtime_3.4.0.v20080512.jar \
 -DrepositoryId=$REPOSITORY_ID \
 -Durl=$REPOSITORY_URL
 
mvn deploy:deploy-file \
 -DgroupId=org.eclipse \
 -DartifactId=org.eclipse.jface.databinding \
 -Dversion=1.2.0 \
 -Dpackaging=jar \
 -Dfile=lib/org.eclipse.jface.databinding_1.2.0.I20080515-2000a.jar \
 -DrepositoryId=$REPOSITORY_ID \
 -Durl=$REPOSITORY_URL
 
 mvn deploy:deploy-file \
 -DgroupId=org.eclipse \
 -DartifactId=org.eclipse.core.databinding \
 -Dversion=1.1.0 \
 -Dpackaging=jar \
 -Dfile=lib/org.eclipse.core.databinding_1.1.0.I20080527-2000.jar \
 -DrepositoryId=$REPOSITORY_ID \
 -Durl=$REPOSITORY_URL
 
mvn deploy:deploy-file \
 -DgroupId=org.eclipse \
 -DartifactId=org.eclipse.core.databinding.beans \
 -Dversion=1.1.0 \
 -Dpackaging=jar \
 -Dfile=lib/org.eclipse.core.databinding.beans_1.1.0.I20080508-2000a.jar \
 -DrepositoryId=$REPOSITORY_ID \
 -Durl=$REPOSITORY_URL
 
mvn deploy:deploy-file \
 -DgroupId=org.eclipse \
 -DartifactId=org.eclipse.core.commands \
 -Dversion=3.4.0 \
 -Dpackaging=jar \
 -Dfile=lib/org.eclipse.core.commands_3.4.0.I20080509-2000.jar \
 -DrepositoryId=$REPOSITORY_ID \
 -Durl=$REPOSITORY_URL
 
mvn deploy:deploy-file \
 -DgroupId=org.eclipse.swt \
 -DartifactId=win32 \
 -Dversion=3 \
 -Dpackaging=jar \
 -Dfile=lib/win32/swt-3.3.2-win32-x86.jar \
 -DrepositoryId=$REPOSITORY_ID \
 -Durl=$REPOSITORY_URL
 
mvn deploy:deploy-file \
 -DgroupId=org.eclipse.swt \
 -DartifactId=macosx \
 -Dversion=3 \
 -Dpackaging=jar \
 -Dfile=lib/osx/swt-3.5-cocoa-macosx-x86_64.jar \
 -DrepositoryId=$REPOSITORY_ID \
 -Durl=$REPOSITORY_URL
 
mvn deploy:deploy-file \
 -DgroupId=ishell \
 -DartifactId=win32 \
 -Dversion=1.0 \
 -Dpackaging=jar \
 -Dfile=lib/win32/ishell-win32.jar \
 -DrepositoryId=$REPOSITORY_ID \
 -Durl=$REPOSITORY_URL
 
mvn deploy:deploy-file \
 -DgroupId=ishell \
 -DartifactId=linux \
 -Dversion=1.0 \
 -Dpackaging=jar \
 -Dfile=lib/linux/ishell-linux.jar \
 -DrepositoryId=$REPOSITORY_ID \
 -Durl=$REPOSITORY_URL
 
mvn deploy:deploy-file \
 -DgroupId=org.eclipse \
 -DartifactId=org.eclipse.cdt.core.win32 \
 -Dversion=4.0.0 \
 -Dpackaging=jar \
 -Dfile=lib/win32/org.eclipse.cdt.core.win32_4.0.0.200709241202.jar \
 -DrepositoryId=$REPOSITORY_ID \
 -Durl=$REPOSITORY_URL
 
 
